### ISSUE TITLE
Trying to play apex legends but I don't have 3rd one in the party 

### ISSUE THREAD

**Issue by ivankozlovcodes** [JohnnyJumper/Discord2.0#1] opened 2022-10-06 03:24 UTC
Steps to reproduce.

- Open Apex legends
Expected: zurzula is in the party
Actual: I'm all alone

**Comment by JohnnyJumper** [comment] 2022-10-06 08:05
This is intended behavior. Zurzula needed to finish the work on the project. 
kozy could help ;) 

Closing this due to common sense.

**Closed as completed by JohnnyJumper** 2022-10-06 08:05 UTC
